#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server.

# Update and Upgrade System Packages
sudo apt update && sudo apt upgrade -y

# Install HAproxy
sudo apt install haproxy -y

# Configure HAProxy
printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
	server 530629-web-01 184.72.128.238:80 check
	server 530629-web-02 54.173.198.127:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
